//
//  Service.swift
//  SwiftUITabView
//
//  Created by Lili on 16/10/2019.
//  Copyright © 2019 Rebeloper. All rights reserved.
//


import Foundation

struct Service {
    static let listData: [ListElement] = [
        ListElement(icon: Constants2.IconNames.icon1,  image: Constants2.ImageNames.image1, title: "ANDROID APP DEVELOPMENT FROM A TO Z", text: "Our experts know every corner of the Android platform, down to its core. We have the experience of working with every Android device type, brand, and custom ecosystem. Our Android app development services will give you a reliable product that appeals to the platform’s users."),
        ListElement(icon: Constants2.IconNames.icon2, image: Constants2.ImageNames.image2, title: "IOS APP DEVELOPMENT SERVICES", text: " DEO helps businesses across all major industries and niches. We will help you choose the right technology stack, create a fitting UX, and integrate the app into your existing infrastructure. Our mobile platform will also make the iOS app development process quicker and more cost-efficient."),
        ListElement(icon: Constants2.IconNames.icon3, image: Constants2.ImageNames.image3, title: "HYBRID APP DEVELOPMENT", text: "While native applications can boost speed and maximize features, web-based apps offer a cost-effective way to provide compatibility with different platforms. Combining the benefits of both into a unique hybrid app framework can yield great benefits.Hybrid mobile application development combines the best of both worlds and allows you to reach a wider audience."),
        ListElement(icon: Constants2.IconNames.icon4, image: Constants2.ImageNames.image4, title: "MICROSOFT AZURE SOLUTIONS ", text: "Microsoft Azure is a cloud platform that provides businesses with the tools they need to build a flexible, scalable, and connected business environment. It is used by 90% of Fortune 500 companies and trusted by U.S. Government institutions. Make your next big leap in Digital Transformation by implementing Azure solutions into your business."),
        ListElement(icon: Constants2.IconNames.icon5, image: Constants2.ImageNames.image5, title: "ENTERPRISE PRODUCT STRATEGY", text: "In today’s rapidly changing business landscape, your company can’t be held back by clumsy or antiquated software. Our deep bench of talented developers and project managers will analyze your challenges, diagnose success blockers, craft a comprehensive strategic product plan, and help you develop a fully-customized software solution designed to streamline efficiencies, cut costs, boost client engagement, and more. We can help you formulate a solid enterprise product strategy. Big Data Management & Processing, Cloud Computing & Workflow Automation, Consulting."),
        ListElement(icon: Constants2.IconNames.icon6, image: Constants2.ImageNames.image6, title: "ENTERPRISE SOFTWARE DEVELOPMENT", text: "We create a wide variety of enterprise software solutions to meet your digital transformation goals and provide your competitive edge. Get your products and services to market faster.We develop enterprise solutions which include project management and collaboration software, CRM and HRM solutions, ERP software, tracking systems, and more.DEO uses the best enterprise applications engineering practices to create solutions that match the business needs of its clients. Our development team has a solid reputation and can develop custom enterprise application software (EAS) from scratch. Besides this, our developers can build and integrate separate EAS modules, and modernize your existing system or its modules to expand overall functionality."),
        ListElement(icon: Constants2.IconNames.icon7, image: Constants2.ImageNames.image7, title: "ARCHITECTURE", text: "We live by the mantra “measure twice, cut once.” By mapping software components out early, you avoid costly mistakes and ensure that software fulfills the task it was designed for. Software architecture can reduce system complexity and ensure systems are flexible and aligned with your business strategy. By supporting development teams in estimating effort, fulfilling technical requirements, and roadmapping.Intellectsoft can respond effectively to a wide range of business needs such as: Project Architecture Support, from project inception to completion, ensuring that solutions are being correctly implemented and augmenting the team if necessary.Software Architecture Design and Modeling, to prioritize the project’s architectural drivers and improve definition of IT strategies for greater predictability and reduced risk.Legacy Modernization Assessment, such as migrating to new tech or refactoring existing solutions."),
        ListElement(icon: Constants2.IconNames.icon8, image: Constants2.ImageNames.image8, title: "UI AND UX DESIGN", text: "From basic event apps to scalable enterprise software for Fortune 500 companies, our long-standing design team can help your any idea come into being with the latest tools and tech. Our well-established process and standardised approach to design will ensure the final product looks and works as you required."),
         ListElement(icon: Constants2.IconNames.icon9, image: Constants2.ImageNames.image9, title: "QA AND SOFTWARE TESTING", text: "Our QA testers join project activities at early stages of product development. This allows us to ensure that nothing in your software is overlooked, and that your product quality complies with the acceptance criteria that were agreed on.")
        
    ]

}
