//
//  Service.swift
//  SwiftUITabView
//
//  Created by Lili on 16/10/2019.
//  Copyright © 2019 Rebeloper. All rights reserved.
//


import Foundation

struct Service {
    static let listData: [ListElement] = [
        ListElement(icon: Constants2.IconNames.icon1,  image: Constants2.ImageNames.image1, title: "HOTEL WEBSITE", text: "Impressive and principally exclusive website templates, designed by the OVERRON team and combine high-aesthetics with the latest Hotel Marketing trends.We design creative and fully functional website templates, absolutely user-friendly, that draw attention to the unique attributes of your business. Our premium templates have a smart, smooth, and modern layout that is easy to customize and make your brand shine.  You can choose the template that suits you best from our extensive template-collection, or you can make a mix & match composition, choosing features from different templates to fully customize your website -  the possibilities are endless!"),
        ListElement(icon: Constants2.IconNames.icon2, image: Constants2.ImageNames.image2, title: "SEO", text: " Search Engine Optimization (SEO) is a fundamental tool that leads to high rankings in search engines like Google. This ranking is organic, meaning that it may not be affected by Pay-Per-Click (PPC) campaigns. SEO consists of all the necessary configurations in a website, that work together to push it up to the 1st page of search engines’ organic results, when users type words and phrases that are related to your brand.Given the fact that most people who do their search online, scroll down and stop at the first page of Google results, it is crucial for your hotel to appear there – ideally among the very first results. It is the only way to ensure your advancement on the “digital highlands”, and your long-lasting presence there. Our SEO experts will skyrocket and secure your business right at the peak of the search engine mountain, showing off your brand for all to see!"),
        ListElement(icon: Constants2.IconNames.icon3, image: Constants2.ImageNames.image3, title: "SOCIAL MEDIA MARKETING", text: "According to official studies, social media play the most important role in the first and last phase of the travel decision-cycle, meaning inspiration and experience. Social media have become over the years a substantial and inevitable part of digital strategy, that can bring upon marvelous marketing opportunities.Social media is not only about posting and repeating yourself. It is about engaging with your followers in a way that will convert likes to actual visitors. Undeniably, every business needs a strong presence in social media, and the OVERRON team is here to help you. Rather than bombarding your followers with nonstop posts, risking to become indifferent and even tiresome, our team performs highly effective social media marketing that is customized on your needs, focused on strengthening your brand, and keeps on expanding your audience."),
        ListElement(icon: Constants2.IconNames.icon4, image: Constants2.ImageNames.image4, title: "GOOGLE ADS", text: "Travel always starts with a search; therefore, it is crucial to get dibs on the front seat of search engines. Google Ads is the fastest way to reach the top of search results (advertised results), allowing you to increase your brand awareness and thus, your revenues!In OVERRON, our Google-certified team has extensive experience in creating Google Ads campaigns that leave a lasting impact, and answer all a searcher’s -and client-to-be- questions. Focused on building fully custom and accurately optimized campaigns, our team will strategically design targeted and compelling campaigns, that combined with the appropriate budget allocation, will increase your bookings and maximize your return on investment."),
        ListElement(icon: Constants2.IconNames.icon5, image: Constants2.ImageNames.image5, title: "BRAND & IDENTITY", text: "From the logo design to business cards, from the shapes and textures to the color palette, the whole identity of a hotel must be artfully conceived, and accurately developed to convey and communicate the philosophy, the public image, as well as the experience linked to the brand. You never know where possible clients may catch a glimpse of your brand, and what emotional evocations, thus connections, they could develop from this encounter.Consistency is everything, and our creative team will make sure your business' public image lays on a solid foundation, presenting a strong, undivided image and a common philosophy throughout. Your brand's strategy will be our guideline to set up your brand visually across multiple touch-points that people can feel and experience. We offer holistic brand identity solutions that will capture people's attention and leave a memorable impression, making your brand recognizable.")
      
        
    ]

}
